function createDeck(seedString) {
  const deck = [];
  for (const suit of SUITS) {
    for (const rank of RANKS) {
      deck.push({
        id: getCardId(suit, rank.r),
        suit,
        rank: rank.r,
        value: rank.v,
      });
    }
  }
  seededShuffle(deck, seedString);
  return deck;
}

function createEmptyState() {
  return {
    deck: [],
    index: 0,
    current: null,
    cheats: [],
    pendingCheatOptions: [],
    pendingCheatAwardQueue: [],
    pendingPowerOptions: [],
    pendingPowerAwardQueue: [],
    pendingRunSeed: "",
    pendingRunDeck: [],
    pendingRunMode: "standard",
    pendingDailyDateKey: "",
    pendingDeckKey: loadSelectedDeck(),
    pendingLevelNumber: loadSelectedLevel(),
    powerChoiceLockedUntil: 0,
    message: "Press Start Run.",
    temporaryMessageText: "",
    temporaryMessageUntil: 0,
    gameOver: true,
    gameOverMessageReady: false,
    gameOverMessageJustReleased: false,
    victoryMessageActive: false,
    victoryMessageJustReleased: false,
    experience: loadExperience(),
    displayExperience: null,
    experienceAwardedForRun: false,
    experienceBanking: null,
    experienceBankedCardIds: new Set(),
    experiencePreviewUntil: 0,
    experienceMilestonesAwarded: new Set(),
    pendingExperienceBonuses: [],
    unusedCheatExperienceAwarded: false,
    handCard: null,
    currentValueModifier: 0,
    nextCardValueModifier: 0,
    correctAnswers: 0,
    streak: 0,
    bestScore: loadBestScore(loadSelectedDeck(), loadSelectedLevel()),
    seenCardIds: new Set(),
    powers: [],
    selectedStartPowerId: null,
    selectedDeckKey: loadSelectedDeck(),
    currentDeckKey: loadSelectedDeck(),
    selectedLevelNumber: loadSelectedLevel(),
    currentLevelNumber: loadSelectedLevel(),
    runDebugLog: loadRunDebugLog(),
    metaProgression: loadMetaProgression(),
    cardStats: loadCardStats(),
    cardBackStatuses: loadCardBackStatuses(),
    cheatUnlocks: loadCheatUnlocks(),
    deckWins: loadDeckWins(),
    deckLevelClears: loadDeckLevelClears(),
    runMode: "standard",
    devMode: false,
    dailyDateKey: "",
    dailyCheatOfferCount: 0,
    dailyPowerOfferCount: 0,
    justUnlockedCheatIds: [],
    cheatChoiceLockedUntil: 0,
    activeCheatAwardReason: "",
    activePowerAwardReason: "",
    pauseForCheat: false,
    cheatUsesOnCurrentCard: 0,
    lucky7Armed: false,
    fiveAliveArmed: false,
    marginForErrorArmed: false,
    hotOrColdArmed: false,
    stitchInTimeArmed: false,
    higherHigherHigherRemaining: 0,
    psychoRemaining: 0,
    godSaveKingArmed: false,
    alwaysBetBlackArmed: false,
    lockySevensActive: false,
    oddOneOutArmed: false,
    cursedShieldArmed: false,
    suitedAndBootedArmed: false,
    suitedAndBootedSuit: "",
    blankSpaceActive: false,
    blankSpaceValue: null,
    forcedNextGuess: "",
    lockCurrentCardForForcedGuess: false,
    cheatACheaterRemaining: 0,
    wlStage: "",
    sixSevenArmed: false,
    sixSevenRewardChoicesRemaining: 0,
    equals11Armed: false,
    catch22Armed: false,
    runSeed: loadLastRunSeed() || randomSeedString(),
    restartConfirmArmed: false,
    deckStatsTooltipOpen: false,
    victoryPromptShown: false,
    currentCardFeedback: "",
    pendingRevealAnimation: null,
    gameOverDisplayCards: null,
    cheatChoiceIntroToken: 0,
    powerChoiceIntroToken: 0,
    cheatChoicePreviewIndex: -1,
    cheatChoiceAnimating: null,
    recentlySeenCardId: "",
    nudgeUpCharges: 0,
    nudgeDownCharges: 0,
    energy: 0,
    lastJokerMessage: "",
  };
}

let state = createEmptyState();
