param(
  [Parameter(Mandatory = $false)]
  [string]$CsvPath = ".\cheat-catalog.csv",

  [Parameter(Mandatory = $false)]
  [string]$OutputPath = ".\js\cheat-balance-overrides.js"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Parse-Bool([string]$value) {
  if ($null -eq $value) { return $null }
  $v = $value.Trim().ToLowerInvariant()
  if ($v -in @("true", "1", "yes", "y")) { return $true }
  if ($v -in @("false", "0", "no", "n")) { return $false }
  return $null
}

function Parse-Int([string]$value) {
  if ([string]::IsNullOrWhiteSpace($value)) { return $null }
  $parsed = 0
  if ([int]::TryParse($value.Trim(), [ref]$parsed)) { return $parsed }
  return $null
}

function Parse-Number([string]$value) {
  if ([string]::IsNullOrWhiteSpace($value)) { return $null }
  $parsed = 0.0
  if ([double]::TryParse($value.Trim(), [ref]$parsed)) { return $parsed }
  return $null
}

if (-not (Test-Path -LiteralPath $CsvPath)) {
  throw "CSV not found: $CsvPath"
}

$rows = Import-Csv -LiteralPath $CsvPath
if ($rows.Count -eq 0) {
  throw "CSV has no rows: $CsvPath"
}

$overrides = @{}
$editableFields = @(
  "name",
  "rarity",
  "unlockAt",
  "included",
  "stacking",
  "weight",
  "poolExcludedIfPowerOwned",
  "description"
)

foreach ($row in $rows) {
  $id = [string]$row.id
  if ([string]::IsNullOrWhiteSpace($id)) { continue }

  $entry = @{}

  foreach ($field in $editableFields) {
    if (-not ($row.PSObject.Properties.Name -contains $field)) { continue }
    $raw = [string]$row.$field
    if ([string]::IsNullOrWhiteSpace($raw)) { continue }

    switch ($field) {
      "unlockAt" {
        $parsed = Parse-Int $raw
        if ($null -ne $parsed) { $entry[$field] = $parsed }
      }
      "weight" {
        $parsed = Parse-Number $raw
        if ($null -ne $parsed) { $entry[$field] = $parsed }
      }
      "included" {
        $parsed = Parse-Bool $raw
        if ($null -ne $parsed) { $entry[$field] = $parsed }
      }
      default {
        $entry[$field] = $raw.Trim()
      }
    }
  }

  if ($entry.Count -gt 0) {
    $overrides[$id.Trim()] = $entry
  }
}

$overridesJson = $overrides | ConvertTo-Json -Depth 8
$generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

$js = @"
/* Auto-generated by tools/import-cheats.ps1 on $generatedAt
 * Source CSV: $CsvPath
 */
window.CHEAT_BALANCE_OVERRIDES = $overridesJson;
"@

$outputDir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDir) -and -not (Test-Path -LiteralPath $outputDir)) {
  New-Item -ItemType Directory -Path $outputDir | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $js -Encoding UTF8

Write-Host "Imported $($overrides.Count) cheat overrides from '$CsvPath'."
Write-Host "Wrote '$OutputPath'."
